import { useEffect, useMemo, useRef, useState } from 'react';
import {
  CircleAlertIcon,
  DownloadIcon,
  PauseIcon,
  PlayIcon,
  XIcon
} from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card';
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle
} from '@/components/ui/empty';
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel
} from '@/components/ui/field';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { cn } from '@/lib/utils';

const voiceOptions = [
  { value: 'de-CH-LeniNeural', label: 'Deutsch (Schweiz) - Leni' },
  { value: 'de-DE-KatjaNeural', label: 'Deutsch (Deutschland) - Katja' },
  { value: 'en-US-JennyNeural', label: 'Englisch (USA) - Jenny' }
];

const examplePresets = [
  {
    id: 'demo-ch',
    label: 'CH Demo',
    text: 'Guten Tag. Diese Demo verwendet Microsoft Azure Speech für die Sprachausgabe.'
  },
  {
    id: 'demo-de',
    label: 'Projekt',
    text: 'Willkommen zu unserem Schulprojekt. Die App wandelt Text direkt im Browser in Audio um.'
  },
  {
    id: 'demo-en',
    label: 'English',
    text: 'Hello. This short example shows an English voice generated by Azure Speech.'
  }
];

function App() {
  const [text, setText] = useState('');
  const [voice, setVoice] = useState(voiceOptions[0].value);
  const [historyItems, setHistoryItems] = useState([]);
  const [selectedEntry, setSelectedEntry] = useState(null);
  const [requestError, setRequestError] = useState('');
  const [historyError, setHistoryError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isHistoryLoading, setIsHistoryLoading] = useState(true);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const audioRef = useRef(null);
  const selectedEntryIdRef = useRef(null);

  useEffect(() => {
    loadHistory();
  }, []);

  useEffect(() => {
    const audio = audioRef.current;

    if (!audio) {
      return;
    }

    if (!selectedEntry?.audioUrl) {
      audio.pause();
      audio.removeAttribute('src');
      audio.load();
      setIsPlaying(false);
      setCurrentTime(0);
      setDuration(0);
      selectedEntryIdRef.current = null;
      return;
    }

    const entryChanged = selectedEntryIdRef.current !== selectedEntry.id;

    if (entryChanged) {
      selectedEntryIdRef.current = selectedEntry.id;
      audio.src = selectedEntry.audioUrl;
      audio.load();
      setCurrentTime(0);
      setDuration(0);
    }

    const playPromise = audio.play();

    if (playPromise && typeof playPromise.catch === 'function') {
      playPromise.catch(() => {
        setIsPlaying(false);
      });
    }
  }, [selectedEntry]);

  const trimmedText = text.trim();
  const selectedPreset =
    examplePresets.find((preset) => preset.text === text) || null;
  const showFieldError = Boolean(requestError) && !trimmedText;
  const showRequestError = Boolean(requestError) && !showFieldError;
  const historyStatus = useMemo(() => {
    if (isHistoryLoading) {
      return 'History wird geladen';
    }

    return `${historyItems.length} Audios gespeichert`;
  }, [historyItems.length, isHistoryLoading]);

  async function loadHistory(preferredEntryId) {
    setIsHistoryLoading(true);
    setHistoryError('');

    try {
      const response = await fetch('/api/history');

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || 'Die History konnte nicht geladen werden.');
      }

      const data = await response.json();
      const items = Array.isArray(data?.items) ? data.items : [];

      setHistoryItems(items);
      setSelectedEntry((currentEntry) => {
        if (preferredEntryId) {
          return items.find((item) => item.id === preferredEntryId) || items[0] || null;
        }

        if (currentEntry) {
          return items.find((item) => item.id === currentEntry.id) || items[0] || null;
        }

        return items[0] || null;
      });
    } catch (error) {
      setHistoryError(error.message || 'Netzwerkfehler beim Laden der History.');
    } finally {
      setIsHistoryLoading(false);
    }
  }

  async function handleSubmit(event) {
    event.preventDefault();

    if (!trimmedText) {
      setRequestError('Bitte gib zuerst einen Text ein.');
      return;
    }

    setIsLoading(true);
    setRequestError('');

    try {
      const response = await fetch('/api/tts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          text: trimmedText,
          voice
        })
      });

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || 'Die Audioausgabe konnte nicht erstellt werden.');
      }

      const data = await response.json();
      const nextEntry = data?.entry;

      if (!nextEntry?.id) {
        throw new Error('History-Eintrag fehlt in der API-Antwort.');
      }

      setText('');
      setHistoryItems((currentItems) => [
        nextEntry,
        ...currentItems.filter((item) => item.id !== nextEntry.id)
      ]);
      setSelectedEntry(nextEntry);
      setHistoryError('');
    } catch (error) {
      setRequestError(error.message || 'Netzwerkfehler beim Aufruf der API.');
    } finally {
      setIsLoading(false);
    }
  }

  function clearComposer() {
    setText('');
    setRequestError('');
  }

  function handlePlayerToggle() {
    const audio = audioRef.current;

    if (!audio || !selectedEntry?.audioUrl) {
      return;
    }

    if (audio.paused) {
      audio.play().catch(() => {
        setIsPlaying(false);
      });
      return;
    }

    audio.pause();
  }

  function handleSeek(event) {
    const audio = audioRef.current;
    const nextTime = Number(event.target.value);

    setCurrentTime(nextTime);

    if (audio) {
      audio.currentTime = nextTime;
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto flex min-h-screen max-w-6xl flex-col px-4 sm:px-6">
        <header className="border-b py-5">
          <h1 className="text-xl font-semibold text-foreground">Text-to-Speech</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {historyStatus}
          </p>
        </header>

        <main className="grid flex-1 gap-6 py-6 lg:min-h-0 lg:grid-cols-[minmax(0,1fr)_360px]">
          <Card className="border-border/80">
            <CardHeader>
              <div>
                <CardTitle>Neues Audio</CardTitle>
                <CardDescription>Text eingeben, Stimme wählen und speichern.</CardDescription>
              </div>
            </CardHeader>

            <CardContent className="flex flex-col gap-5">
              {showRequestError ? (
                <Alert variant="destructive">
                  <CircleAlertIcon />
                  <AlertTitle>Fehler</AlertTitle>
                  <AlertDescription>{requestError}</AlertDescription>
                </Alert>
              ) : null}

              <form className="flex flex-col gap-5" onSubmit={handleSubmit}>
                <FieldGroup>
                  <Field>
                    <FieldLabel>Beispiele</FieldLabel>
                    <ToggleGroup
                      type="single"
                      size="sm"
                      spacing={1}
                      value={selectedPreset?.text || ''}
                      onValueChange={(value) => {
                        if (value) {
                          setText(value);
                          setRequestError('');
                        }
                      }}
                      className="flex flex-wrap justify-start gap-2"
                    >
                      {examplePresets.map((preset) => (
                        <ToggleGroupItem
                          key={preset.id}
                          value={preset.text}
                          variant="outline"
                          className="border-input bg-background px-3 data-[state=on]:border-border data-[state=on]:bg-muted"
                        >
                          {preset.label}
                        </ToggleGroupItem>
                      ))}
                    </ToggleGroup>
                  </Field>

                  <Field>
                    <FieldLabel htmlFor="voice-select">Stimme</FieldLabel>
                    <Select value={voice} onValueChange={setVoice}>
                      <SelectTrigger id="voice-select" className="w-full">
                        <SelectValue placeholder="Stimme wählen" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectGroup>
                          {voiceOptions.map((option) => (
                            <SelectItem key={option.value} value={option.value}>
                              {option.label}
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                  </Field>

                  <Field data-invalid={showFieldError || undefined}>
                    <FieldLabel htmlFor="text-input">Text</FieldLabel>
                    <Textarea
                      id="text-input"
                      value={text}
                      onChange={(event) => {
                        setText(event.target.value);
                        setRequestError('');
                      }}
                      placeholder="Gib hier deinen Text ein..."
                      aria-invalid={showFieldError || undefined}
                      className="min-h-48 resize-none"
                    />
                    <FieldDescription>{trimmedText.length} Zeichen</FieldDescription>
                    {showFieldError ? <FieldError>{requestError}</FieldError> : null}
                  </Field>
                </FieldGroup>

                <div className="flex gap-2">
                  <Button type="submit" size="sm" disabled={isLoading}>
                    {isLoading ? (
                      <Spinner data-icon="inline-start" />
                    ) : (
                      <PlayIcon data-icon="inline-start" />
                    )}
                    Audio erstellen
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    disabled={isLoading || !text}
                    onClick={clearComposer}
                  >
                    <XIcon data-icon="inline-start" />
                    Leeren
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>

          <div className="grid gap-6 lg:min-h-0 lg:grid-rows-[auto_1fr]">
            <Card className="border-border/80">
              <CardHeader>
                <div>
                  <CardTitle>Aktuelle Datei</CardTitle>
                  <CardDescription>Ausgewählter History-Eintrag</CardDescription>
                </div>
                {selectedEntry?.downloadUrl ? (
                  <Button asChild variant="outline" size="sm">
                    <a href={selectedEntry.downloadUrl} download={selectedEntry.blobName}>
                      <DownloadIcon data-icon="inline-start" />
                      Download
                    </a>
                  </Button>
                ) : null}
              </CardHeader>

              <CardContent className="flex flex-col gap-4">
                <audio
                  ref={audioRef}
                  className="hidden"
                  preload="metadata"
                  onLoadedMetadata={() => {
                    const audio = audioRef.current;

                    if (audio) {
                      setDuration(Number.isFinite(audio.duration) ? audio.duration : 0);
                    }
                  }}
                  onTimeUpdate={() => {
                    const audio = audioRef.current;

                    if (audio) {
                      setCurrentTime(audio.currentTime);
                    }
                  }}
                  onPlay={() => setIsPlaying(true)}
                  onPause={() => setIsPlaying(false)}
                  onEnded={() => {
                    setIsPlaying(false);
                    setCurrentTime(0);
                  }}
                />

                {selectedEntry?.audioUrl ? (
                  <>
                    <div className="space-y-2">
                      <p className="text-sm font-medium text-foreground">{selectedEntry.text}</p>
                      <div className="text-xs text-muted-foreground">
                        {getVoiceLabel(selectedEntry.voice)} · {formatTimestamp(selectedEntry.timestamp)}
                      </div>
                    </div>

                    <Separator />

                    <div className="flex flex-col gap-3">
                      <div className="flex items-center gap-3">
                        <Button
                          type="button"
                          variant="outline"
                          size="icon-sm"
                          onClick={handlePlayerToggle}
                        >
                          {isPlaying ? <PauseIcon /> : <PlayIcon />}
                        </Button>

                        <div className="min-w-0 flex-1">
                          <input
                            type="range"
                            min="0"
                            max={duration || 0}
                            step="0.1"
                            value={Math.min(currentTime, duration || 0)}
                            onChange={handleSeek}
                            className="w-full accent-[var(--color-primary)]"
                          />
                        </div>

                        <div className="w-20 text-right text-xs tabular-nums text-muted-foreground">
                          {formatPlaybackTime(currentTime)} / {formatPlaybackTime(duration)}
                        </div>
                      </div>
                    </div>
                  </>
                ) : (
                  <Empty className="border border-dashed border-border/80 py-8">
                    <EmptyHeader>
                      <EmptyMedia variant="icon">
                        <PlayIcon />
                      </EmptyMedia>
                      <EmptyTitle>Keine Datei ausgewählt</EmptyTitle>
                      <EmptyDescription>
                        Wähle einen Eintrag aus der History oder erzeuge eine neue Datei.
                      </EmptyDescription>
                    </EmptyHeader>
                  </Empty>
                )}
              </CardContent>
            </Card>

            <Card className="border-border/80">
              <CardHeader>
                <div>
                  <CardTitle>History</CardTitle>
                  <CardDescription>Gespeicherte Audios aus Blob Storage</CardDescription>
                </div>
              </CardHeader>

              <CardContent className="flex h-full flex-col gap-3 lg:min-h-0">
                {historyError ? (
                  <Alert variant="destructive">
                    <CircleAlertIcon />
                    <AlertTitle>History-Fehler</AlertTitle>
                    <AlertDescription>{historyError}</AlertDescription>
                  </Alert>
                ) : null}

                {isHistoryLoading ? (
                  <div className="flex items-center gap-3 rounded-lg border border-dashed border-border/80 px-4 py-6 text-sm text-muted-foreground">
                    <Spinner />
                    History wird geladen...
                  </div>
                ) : historyItems.length > 0 ? (
                  <div className="flex flex-col gap-1 lg:min-h-0 lg:overflow-auto">
                    {historyItems.map((item) => {
                      const isActive = selectedEntry?.id === item.id;

                      return (
                        <button
                          key={item.id}
                          type="button"
                          onClick={() => setSelectedEntry(item)}
                          className={cn(
                            'flex items-start gap-3 rounded-lg border px-3 py-3 text-left transition-colors',
                            isActive
                              ? 'border-foreground/20 bg-muted'
                              : 'border-transparent hover:border-border hover:bg-muted/60'
                          )}
                        >
                          <div className="min-w-0 flex-1">
                            <p className="truncate text-sm font-medium text-foreground">
                              {item.text}
                            </p>
                            <div className="mt-1 text-xs text-muted-foreground">
                              {formatTimestamp(item.timestamp)} · {getVoiceLabel(item.voice)}
                            </div>
                          </div>
                        </button>
                      );
                    })}
                  </div>
                ) : (
                  <Empty className="border border-dashed border-border/80 py-8">
                    <EmptyHeader>
                      <EmptyMedia variant="icon">
                        <PlayIcon />
                      </EmptyMedia>
                      <EmptyTitle>Keine Einträge</EmptyTitle>
                      <EmptyDescription>
                        Nach der ersten Generierung erscheint die Datei hier.
                      </EmptyDescription>
                    </EmptyHeader>
                  </Empty>
                )}
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}

function getVoiceLabel(voiceValue) {
  return (
    voiceOptions.find((option) => option.value === voiceValue)?.label || voiceValue || '-'
  );
}

function formatTimestamp(timestamp) {
  if (!timestamp) {
    return '-';
  }

  const date = new Date(timestamp);

  if (Number.isNaN(date.getTime())) {
    return timestamp;
  }

  return new Intl.DateTimeFormat('de-CH', {
    dateStyle: 'medium',
    timeStyle: 'short'
  }).format(date);
}

function formatPlaybackTime(value) {
  if (!Number.isFinite(value) || value <= 0) {
    return '0:00';
  }

  const minutes = Math.floor(value / 60);
  const seconds = Math.floor(value % 60);

  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

export default App;
