import { useState } from 'react';

const STORAGE_KEY = 'tts-last-text';

const voiceOptions = [
  {
    value: 'de-CH-LeniNeural',
    label: 'Deutsch (Schweiz) - Leni'
  },
  {
    value: 'de-DE-KatjaNeural',
    label: 'Deutsch (Deutschland) - Katja'
  },
  {
    value: 'en-US-JennyNeural',
    label: 'Englisch (USA) - Jenny'
  }
];

const exampleTexts = [
  'Guten Tag. Diese Demo verwendet Microsoft Azure Speech fuer die Sprachausgabe.',
  'Willkommen zu unserem Schulprojekt. Die App wandelt Text direkt im Browser in Audio um.',
  'Hello. This short example shows an English voice generated by Azure Speech.'
];

function getInitialText() {
  if (typeof window === 'undefined') {
    return '';
  }

  return window.localStorage.getItem(STORAGE_KEY) || '';
}

function App() {
  const [text, setText] = useState(getInitialText);
  const [voice, setVoice] = useState(voiceOptions[0].value);
  const [audioUrl, setAudioUrl] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  function updateText(nextText) {
    setText(nextText);
    window.localStorage.setItem(STORAGE_KEY, nextText);
  }

  function clearAudioUrl() {
    if (audioUrl) {
      window.URL.revokeObjectURL(audioUrl);
      setAudioUrl('');
    }
  }

  async function handleSubmit(event) {
    event.preventDefault();

    const trimmedText = text.trim();

    if (!trimmedText) {
      setError('Bitte gib zuerst einen Text ein.');
      clearAudioUrl();
      return;
    }

    setIsLoading(true);
    setError('');
    clearAudioUrl();

    try {
      const response = await fetch('/api/tts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          text: trimmedText,
          voice
        })
      });

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || 'Die Audioausgabe konnte nicht erstellt werden.');
      }

      const audioBlob = await response.blob();
      const nextAudioUrl = window.URL.createObjectURL(audioBlob);
      setAudioUrl(nextAudioUrl);
    } catch (requestError) {
      setError(requestError.message || 'Netzwerkfehler beim Aufruf der API.');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="header-inner">
          <h1>Text-to-Speech mit Azure Speech</h1>
          <p>
            Eine einfache Web-App fuer ein Schulprojekt. Der eingegebene Text
            wird im Backend mit Microsoft Azure Speech in Sprache umgewandelt.
          </p>
        </div>
      </header>

      <main className="main-content">
        <section className="panel">
          <form className="tts-form" onSubmit={handleSubmit}>
            <div className="field">
              <label htmlFor="text-input">Text</label>
              <textarea
                id="text-input"
                value={text}
                onChange={(event) => updateText(event.target.value)}
                placeholder="Gib hier deinen Text ein..."
                rows="7"
              />
            </div>

            <div className="field">
              <label htmlFor="voice-select">Stimme</label>
              <select
                id="voice-select"
                value={voice}
                onChange={(event) => setVoice(event.target.value)}
              >
                {voiceOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </div>

            <div className="field">
              <span className="field-label">Beispieltexte</span>
              <div className="example-list">
                {exampleTexts.map((exampleText) => (
                  <button
                    key={exampleText}
                    type="button"
                    className="example-button"
                    onClick={() => updateText(exampleText)}
                  >
                    {exampleText}
                  </button>
                ))}
              </div>
            </div>

            <button className="submit-button" type="submit" disabled={isLoading}>
              {isLoading ? 'Audio wird erstellt...' : 'Text in Sprache umwandeln'}
            </button>
          </form>
        </section>

        {error ? (
          <section className="panel message-panel error-panel" role="alert">
            <h2>Fehler</h2>
            <p>{error}</p>
          </section>
        ) : null}

        <section className="panel message-panel">
          <h2>Audio</h2>
          {audioUrl ? (
            <audio controls src={audioUrl} className="audio-player">
              Dein Browser unterstuetzt das Audio-Element nicht.
            </audio>
          ) : (
            <p className="hint">
              Nach dem Absenden erscheint hier der Audio-Player mit der
              generierten Sprachausgabe.
            </p>
          )}
        </section>
      </main>
    </div>
  );
}

export default App;
